
import { GoogleGenAI } from "@google/genai";

const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      // Result is a data URL: "data:image/jpeg;base64,..."
      // We only need the base64 part
      const result = reader.result as string;
      resolve(result.split(',')[1]);
    };
    reader.onerror = error => reject(error);
  });
};

export const generateIconFromIllustrations = async (
  styleImages: File[],
  prompt: string,
  contentImage?: File
): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set.");
  }
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  try {
    const styleImageParts = await Promise.all(
      styleImages.map(async (file) => {
        const base64Data = await fileToBase64(file);
        return {
          inlineData: {
            data: base64Data,
            mimeType: file.type,
          },
        };
      })
    );

    // FIX: Explicitly type contentParts to allow both image and text parts.
    const contentParts: ({ inlineData: { data: string; mimeType: string; } } | { text: string })[] = [...styleImageParts];
    let fullPrompt: string;

    if (contentImage) {
      const contentImageBase64 = await fileToBase64(contentImage);
      contentParts.push({
        inlineData: {
          data: contentImageBase64,
          mimeType: contentImage.type,
        },
      });
      fullPrompt = `The first set of images define the artistic style. The second image is a visual reference for the subject matter. Generate an icon in the style of the first images, depicting: "${prompt}". The subject is also shown in the second image.`
    } else {
      fullPrompt = `Generate a new icon based on the style of the provided illustrations. The icon should be: ${prompt}`;
    }
    
    contentParts.push({ text: fullPrompt });

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: contentParts,
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        const mimeType = part.inlineData.mimeType;
        return `data:${mimeType};base64,${base64ImageBytes}`;
      }
    }

    throw new Error('No image was generated by the model.');

  } catch (error) {
    console.error("Error generating icon:", error);
    if (error instanceof Error) {
        throw new Error(`Failed to generate icon: ${error.message}`);
    }
    throw new Error('An unknown error occurred while communicating with the API.');
  }
};
